import { SenderData } from "@/interface/DelivaryData";

export const activeDelivaryData: SenderData[] = [
  {
    senderId: 201,
    name: "Nusrat Jahan",
    senderProfileStatus: "Verified",
    contactInfo: "+8801712345678",
    email: "nusrat.jahan@example.com",
    senderWeight: 8,
    senderPrice: 750,
    delivarystatus: "In Progress",
    tripData: {
      tripId: 501,
      from: "Dhaka",
      to: "Comilla",
      date: "2025-11-14",
      carryWeight: 10,
      note: "Contains documents and fragile glass items.",
      transportType: "Bus",
      price: 750,
    },
  },
  {
    senderId: 202,
    name: "Rafi Ahmed",
    senderProfileStatus: "Verified",
    contactInfo: "+8801998765432",
    email: "rafi.ahmed@example.com",
    senderWeight: 15,
    senderPrice: 1300,
    delivarystatus: "In Progress",
    tripData: {
      tripId: 502,
      from: "Sylhet",
      to: "Dhaka",
      date: "2025-11-18",
      carryWeight: 20,
      note: "Carrying handmade crafts and clothes.",
      transportType: "Train",
      price: 1300,
    },
  },
  {
    senderId: 203,
    name: "Tania Rahman",
    senderProfileStatus: "Verified",
    contactInfo: "+8801887654321",
    email: "tania.rahman@example.com",
    senderWeight: 5,
    senderPrice: 600,
    delivarystatus: "In Progress",
    tripData: {
      tripId: 503,
      from: "Khulna",
      to: "Dhaka",
      date: "2025-11-10",
      carryWeight: 7,
      note: "Small package — includes books and stationery.",
      transportType: "Car",
      price: 600,
    },
  },
    {
    senderId: 208,
    name: "Shihab Rahman",
    senderProfileStatus: "Verified",
    contactInfo: "+8801887654321",
    email: "shihab.rahman@example.com",
    senderWeight: 5,
    senderPrice: 400,
    delivarystatus: "In Progress",
    tripData: {
      tripId: 503,
      from: "Chattogram",
      to: "Dhaka",
      date: "2025-11-10",
      carryWeight: 7,
      note: "Small package — includes books and stationery.",
      transportType: "Car",
      price: 600,
    },
  },
    {
    senderId: 208,
    name: "Shihab Rahman",
    senderProfileStatus: "Verified",
    contactInfo: "+8801887654321",
    email: "shihab.rahman@example.com",
    senderWeight: 5,
    senderPrice: 400,
    delivarystatus: "Delivered",
    tripData: {
      tripId: 503,
      from: "Feni",
      to: "Gaibandha",
      date: "2025-11-10",
      carryWeight: 7,
      note: "Big package — includes books and stationery.",
      transportType: "Car",
      price: 600,
    },
  },
];
