import { DelivaryData } from "@/interface/DelivaryData";

export const senderData:DelivaryData[] = [
  {
    name: "Abdul Karim",
    tripData: {
      from: "Dhaka",
      to: "Chittagong",
      carryWeight: 12,
      date: "2025-11-12",
      note: "Carrying fragile items, handle with care.",
    },
    id: "Verified",
    senderStatus: "On the way",
    userRating: 4.8,
    isTravelling: true,
  },
  {
    name: "Mehedy Hasan",
    tripData: {
      from: "Khulna",
      to: "Dhaka",
      carryWeight: 20,
      date: "2025-11-15",
      note: "Package contains electronics.",
    },
    id: "Unverified",
    senderStatus: "Pending",
    userRating: 4.5,
    isTravelling: false,
  },
  {
    name: "Nusrat Jahan",
    tripData: {
      from: "Sylhet",
      to: "Rajshahi",
      carryWeight: 8,
      date: "2025-11-10",
      note: "Perishable goods, deliver quickly.",
    },
    id: "Verified",
    senderStatus: "Delivered",
    userRating: 4.9,
    isTravelling: true,
  },
  {
    name: "Rafiq Uddin",
    tripData: {
      from: "Comilla",
      to: "Barisal",
      carryWeight: 10,
      date: "2025-11-20",
      note: "Documents only.",
    },
    id: "Unverified",
    senderStatus: "Pending",
    userRating: 3.8,
    isTravelling: false,
  },
  {
    name: "Sadia Islam",
    tripData: {
      from: "Jessore",
      to: "Dhaka",
      carryWeight: 15,
      date: "2025-11-18",
      note: "Contains books and stationery.",
    },
    id: "Verified",
    senderStatus: "On the way",
    userRating: 4.6,
    isTravelling: true,
  },
  {
    name: "Tanvir Ahmed",
    tripData: {
      from: "Rajshahi",
      to: "Sylhet",
      carryWeight: 5,
      date: "2025-11-25",
      note: "Small parcel for urgent delivery.",
    },
    id: "Unverified",
    senderStatus: "Pending",
    userRating: 4.1,
    isTravelling: false,
  },
  {
    name: "Lamia Noor",
    tripData: {
      from: "Bogura",
      to: "Dhaka",
      carryWeight: 9,
      date: "2025-11-22",
      note: "Clothing items for delivery.",
    },
    id: "Verified",
    senderStatus: "Delivered",
    userRating: 4.7,
    isTravelling: true,
  },
  {
    name: "Arif Chowdhury",
    tripData: {
      from: "Rangpur",
      to: "Dhaka",
      carryWeight: 25,
      date: "2025-11-17",
      note: "Large shipment, need extra space.",
    },
    id: "Unverified",
    senderStatus: "On the way",
    userRating: 3.9,
    isTravelling: false,
  },
  {
    name: "Sharmin Akter",
    tripData: {
      from: "Chittagong",
      to: "Khulna",
      carryWeight: 18,
      date: "2025-11-14",
      note: "Household goods, careful handling required.",
    },
    id: "Verified",
    senderStatus: "Delivered",
    userRating: 4.8,
    isTravelling: true,
  },
  {
    name: "Imran Hossain",
    tripData: {
      from: "Dhaka",
      to: "Sylhet",
      carryWeight: 7,
      date: "2025-11-11",
      note: "Confidential documents enclosed.",
    },
    id: "Unverified",
    senderStatus: "Pending",
    userRating: 4.0,
    isTravelling: false,
  },
  {
    name: "Rehana Begum",
    tripData: {
      from: "Barisal",
      to: "Rajshahi",
      carryWeight: 13,
      date: "2025-11-23",
      note: "Grocery items for family delivery.",
    },
    id: "Verified",
    senderStatus: "On the way",
    userRating: 4.9,
    isTravelling: true,
  },
  {
    name: "Fahim Rahman",
    tripData: {
      from: "Sylhet",
      to: "Dhaka",
      carryWeight: 11,
      date: "2025-11-16",
      note: "Personal luggage, fragile items included.",
    },
    id: "Unverified",
    senderStatus: "Pending",
    userRating: 4.3,
    isTravelling: false,
  },
];
